### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [FloEll/QWaterModel#1]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by FloEll** [comment]
Hi Paolo,

oh, I'm very sorry, I removed all unnecessary files (or at least the ones that were obvious to me).

I hope it is fine now. It is my first plugin so I'm not so experienced.


I attached the new plugin zip to this email and also a folder with example data to test the plugin (I don't know if this is necessary).

Thanks.

 

Kind Regards,

Florian Ellsäßer

 

Gesendet: Mittwoch, 29. Januar 2020 um 15:46 Uhr
Von: "Paolo Cavallini" <notifications@github.com>
An: FloEll/QWaterModel <QWaterModel@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [FloEll/QWaterModel] Please remove unnecessary files (#1)


.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by FloEll** [comment]
Ok, I deleted it from the git too.
