### ISSUE TITLE
Astropy package missing

### ISSUE THREAD

**Issue by berkayoruc** [FloEll/QWaterModel#2]
You should store package in plugin

> Couldn't load plugin 'qwatermodel' due to an error when calling its classFactory() method 
> 
> ModuleNotFoundError: No module named 'astropy' 
> Traceback (most recent call last):
>   File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/Users/berkayoruc/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/__init__.py", line 35, in classFactory
>     from .qwatermodel import QWaterModel
>   File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/Users/berkayoruc/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qwatermodel/qwatermodel.py", line 44, in 
>     import astropy.coordinates as coord
>   File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'astropy'

**Comment by FloEll** [comment]
yes, sry that is not ideal. I'm currently working on version 0.2 which works without astropy.

**Comment by FloEll** [comment]
Ok, version 0.2 works without the astropy package :) You can download it from the repository now.

**Comment by berkayoruc** [comment]
Thank you.
