### ISSUE TITLE
How to estimate daily evapotranspiration 

### ISSUE THREAD

**Issue by Annisamunir** [FloEll/QWaterModel#4]
Dear Prof. F. Ellsaßer
How to estimate daily evapotranspiration from this plugin? Is it by changing the time period to 86400s (24 hours) or changing it according to the length of the day?
Kindly Regards.

**Comment by FloEll** [comment]
Dear Annisamunir,
yes, that is possible in principle. 
However I cannot really recommend it. The daily evaporation estimate will be quite inaccurate. Your input image is more like a snapshot and it cannot really represent the whole daily course of surface temperatures. 
With QWaterModel I would not do more than 4 hours from a single thermal image. 
Hope that helped!

**Comment by Annisamunir** [comment]
Thank you for your reply, professor. 
I am so interested in this plugin for my thesis topics, but I'm still a little bit confused because I want to estimate evapotranspiration of several land-use using LST maps from Landsat 8. Is it possible to use the LST map from Landsat 8? and is there any specific condition for the AOI (Area of Interest)?  like the minimum area or area of canopies? 
Kindly Regards.

**Comment by FloEll** [comment]
This is a very exciting research topic! Of course you can use land surface temperatures based on Landsat data. You have several options to extract the land surface temperatures from satellite data:
You could use the methodology and plugin described here: https://www.mdpi.com/2072-4292/8/5/413/htm 
Or you could use the Semi-Automatic Classification Plugin https://plugins.qgis.org/plugins/SemiAutomaticClassificationPlugin/ and maybe this workflow here: https://fromgistors.blogspot.com/2016/09/estimation-of-land-surface-temperature.html
There are many other options too, maybe some would be easier to apply for your specific use case. 
We also discussed quite a lot about the area of interest and how scalable it actually is. The QWaterModel Plugin is based on the DATTUTDUT energy-balance model that was developed and tested on relatively large areas also with satellite data in the original paper: https://link.springer.com/article/10.1515/acgeo-2015-0016
For a minimum area, I got quite good results still for a plantation and a single plant scale e.g. here: https://www.mdpi.com/2072-4292/12/24/4070 
Btw I'm just a postdoc, not a professor, but I'm still happy to answer all your questions :)

**Comment by Annisamunir** [comment]
I apologize for my mistake, sir. Thank you so much for your insights. I appreciate you taking the time to share these very useful resources!

**Comment by FloEll** [comment]
No problem :) 
If you don't mind, I would close the issue here now, but you can re-open it anytime again if you have more questions. 
Have a great day!
