### ISSUE TITLE
For Landsat 7 data

### ISSUE THREAD

**Issue by Elifnyurdakul1** [FloEll/QWaterModel#5]
Is it possible to use gapfilled Landsat 7 image with qwatermodel? I've tried many times for the different versions of the gapfilled landsat 7 image and also tried to create the qwatermodel output with raw data and then tried to gapfill it but couldn't reach a reliable result. Do you have any recommendation for this? Thank you.

**Comment by FloEll** [comment]
Hi Elifnyurdakul1, thanks for reporting this issue. And sorry that I'm only replying now, it has been a busy week. I have actually never tried to use gap-filled Landsat 7 maps with QWaterModel. The 'regular' Landsat images should work though. Can you send me a link or so to download your gap-filled files, so I can see if I can fix the issue? 
Thanks :)

**Comment by Elifnyurdakul1** [comment]
Thank you so much for your concern, I'm actually having trouble with importing the gapfilled and brightness temperature calibrated satellite image into qgis, the value range are changing (Range should be max 302.458-min 283.612 for the data I'm sending but while I'm opening it in qgis, it turns to max 302 - min 0). Even so Im'm sending that gapfilled image with this link: https://drive.google.com/file/d/17l8jda3TX5T1nGNtA8MH5CB5pM-rFKGu/view?usp=sharing 
Thank you :)

**Comment by FloEll** [comment]
You are completely right, If I import your file into QGIS your borders/NaN values are imported as zeros. This is not a big deal, you'll just have to install another version QWaterModel: check for the experimental version 0.4 https://plugins.qgis.org/plugins/qwatermodel/ In this version you can define NaN value input raster (optional), just type a 0 in there :) 
Hope that helped, it would be interesting to hear your feedback if it worked for you too and your general impression on the QWaterModel. Maybe you have some additional ideas that I could inplement?

**Comment by FloEll** [comment]
Dear Elifnyurdakul1, I just wanted to ask if using the experimental QWaterModel v0.4 worked for your data? If so, I would close this issue and I'll publish a new non-experimental version of QWaterModel anyways soon, that would include this functionality. Or do you need further information or help? 
Cheers!
